baseurl                  = "https://ntk148v.github.io/blog"
languageCode             = "en-us"
title                    = "Hello World!"
theme                    = "sam"
pygmentsStyle            = "monokai"
pygmentsCodefences       = true

[params]
    dateform             = "Mon Jan 02, 2006"
    dateformfull         = "Mon Jan 2 2006 15:04:05 EST"
    favicon              = "/sam.ico"
    homepage             = "main"                        # What to call the home page link
    galleryFolder        = "images/"                     # Where you've put your images, after "/content/gallery/" (eg. "images/")
    clickablePhotos      = true                          # Allow links to the full size images
    smallPreviewImages   = false                         # Show thumbnails (small images) instead of using full size images on the gallery page
                                                         # Note: This will only become active if clickablePhotos is also true.
    smallImagesSubfolder = "small/"                      # Folder for image thumbnails (small versions) after "/content/gallery/[galleryFolder]" (eg. "small/")
                                                         # For each image the small version has to have the same filename as the big version.
    footerText           = "Call me Sam, a theme for Hugo."

# Metadata
    description          = "Blog site using Hugo + Sam theme."            # Max 160 characters show in search results
    twitterCard          = "summary_large_image"         # Card value “summary”, “summary_large_image”, “app”, or “player”
    primaryImage         = "/tn.png"                     # Image that shows on Twitter cards and OpenGraph links

[[params.mainMenu]]
    link = "/blog/posts"
    text = "posts"

[[params.mainMenu]]
    link = "/blog/gallery"
    text = "gallery"

[[params.mainMenu]]
    link = "/blog/about"
    text = "who is Kien Nguyen?"
